# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XseedRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XseedRN
  pod 'AppCenter/Crashes', '~> 1.0.1'
  pod 'AppCenter/Analytics', '~> 1.0.1'
  pod 'AppCenterReactNativeShared', '~> 1.0.1'

  


  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'XseedRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'XseedRN-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XseedRN-tvOS

  target 'XseedRN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
